name: Codehenge
description: Who built it, and why? A blog about software, technology, and more
meta_description: "Codehenge Software Blog"

markdown: redcarpet
highlighter: pygments
logo: true
paginate: 10
baseurl: /
domain_name: 'http://www.codehenge.net'
permalink:     '/:year/:month/:title/'
google_analytics: 'UA-11550677-2'

# Details for the RSS feed generator
url:            'http://www.codehenge.net'
author:         'Constantine Aaron Cois'

# gems
gems:
  - jekyll-redirect-from
  - jekyll-feed

whitelist:
  - jekyll-redirect-from
  - jekyll-feed
